<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>OSM Route Tools</title>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.2/dist/leaflet.css" integrity="sha256-sA+zWATbFveLLNqWO2gtiw3HL/lh1giY/Inf1BJ0z14=" crossorigin=""/>
	<script src="https://unpkg.com/leaflet@1.9.2/dist/leaflet.js" integrity="sha256-o9N1jGDZrf5tS+Ft4gbIK7mYMipq9lqpVJ91xHSyKhg=" crossorigin=""></script>
	<script type="text/javascript" src="http://code.jquery.com/jquery-1.7.2.min.js"></script>
	<script type="text/javascript" src="map.js"></script>
	<script type="text/javascript">
<%!
    import simplejson as json
    def j(d):
        return json.dumps(d)
%>
var lines = ${j(lines)};

	</script>
	<link rel="stylesheet" type="text/css" href="style.css" />
</head>
<body>
	<%include file="/header.tpl" args="page='map'" />
	<h2>Map: ${profile['maps'][mapkey][0]}</h2>
	<p>Paths are generated by connecting the route's node-members that look like stops. The contained ways are ignored.</p>
	<div id="map"></div>
	<%include file="/footer.tpl" />
</body>
</html>
